name: Deploy server and socket for AD Displays

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.16.0"

      # Build Admin Dashboard
      - name: Install dependencies and build admin dashboard
        working-directory: ./Ad-displays-admin-dashboard
        run: |
          npm install
          npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Build Socket App
      - name: Install dependencies and build socket app
        working-directory: ./Ad-displays-socket
        run: |
          npm install
          npm run build
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_SERVER: ${{ secrets.DB_HOST }}

      # Start or create PM2 processes
      - name: Start apps with PM2
        shell: cmd
        run: |
          REM Navigate to GitHub workspace
          cd %GITHUB_WORKSPACE%

          REM Start Admin Dashboard via CMD script
          pm2 start Ad-displays-admin-dashboard\start-dashboard.cmd --name ad-dashboard --interpreter cmd

          REM Start Socket App via CMD script
          pm2 start Ad-displays-socket\start-socket.cmd --name ad-socket --interpreter cmd

          REM Save PM2 process list for startup
          pm2 save
